{ pkgs, inputs, ... }:

{
  # CLI tools, native nixpkgs. Sorted by attribute name; `dot package add <x>`
  # (type pkg) inserts here. Rust toolchain = cargo + rustc + clippy + rustfmt.
  environment.systemPackages = with pkgs; [
    ast-grep
    awscli2
    bash-language-server
    biome
    btop
    cargo
    clippy
    cloc
    cloudflared
    cmake
    direnv
    doggo
    fd
    ffmpeg
    fish
    fzf
    gh
    git
    gnupg
    gnused
    go
    jq
    just
    kitty
    lazygit
    llvm
    llvm.dev # provides llvm-config (separate dev output)
    lua-language-server
    marksman
    mpv
    neovim
    nodejs_latest
    oxlint
    prettierd
    python314
    rclone
    ripgrep
    rust-analyzer
    rustc
    rustfmt
    shellcheck
    sqls
    starship
    stylua
    svelte-language-server
    tailwindcss-language-server
    tmux
    tree
    tree-sitter
    ty
    uv
    vscode-langservers-extracted
    wasm-tools
    wasmtime
    wget
    wireguard-tools
    yaml-language-server
    yazi
    zig
    zls
    zoxide
  ];
}
