# vim:fileencoding=utf-8:ft=conf
# Ensures that the configuration file is encoded in UTF-8 and uses marker-based folding.

font_size 16.0
# Sets the font size to 16.0 points.
text_composition_strategy 1.0 0
shell_integration disabled
enable_audio_bell no
visual_bell_duration 0.0

macos_option_as_alt left

allow_remote_control yes
listen_on unix:/tmp/kitty

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '/Users/ricardoferreira/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
# Browse scrollback buffer in nvim
map cmd+s kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map cmd+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
select_by_word_characters @-./_~?&=%+#

show_hyperlink_targets yes

map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard

copy_on_select yes

# Text selection settings
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url

# delete whole line back to cursor
map cmd+backspace send_text all \x15

# clear the terminal screen
map cmd+shift+backspace combine : clear_terminal scrollback active : send_text all \x0c

# jump to beginning and end of word
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# jump to beginning and end of line
map cmd+left send_text all \x01
map cmd+right send_text all \x05

# Map cmd + <num> to corresponding tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# changing font sizes
map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0
map cmd+0 change_font_size all 0

mouse_map ctrl+alt+left press ungrabbed mouse_selection rectangle
mouse_map left doublepress ungrabbed mouse_selection word
mouse_map left press ungrabbed mouse_selection normal

# navigate between windows
map cmd+h neighboring_window left
map cmd+l neighboring_window right
map cmd+k neighboring_window down
map cmd+j neighboring_window up
map cmd+d close_window

# resize the active split
map cmd+shift+h resize_window narrower
map cmd+shift+l resize_window wider
map cmd+shift+k resize_window taller
map cmd+shift+j resize_window shorter

enabled_layouts splits,stack

# create splits (new window inherits current dir)
map cmd+enter launch --cwd=current --location=vsplit
map cmd+shift+enter launch --cwd=current --location=hsplit
# toggle a single window to fullscreen (uses the stack layout)
map cmd+f toggle_layout stack

action_alias launch_tab launch --cwd=current --type=tab
action_alias launch_window launch --cwd=current

map f1 launch_window nvim
map f2 launch_window lazygit
map f3 launch_window yazi
# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
