# Fish shell completions for dot command
# Auto-generated by dot completions command

# Main command completions
complete -c dot -f

# Commands
complete -c dot -n "__fish_use_subcommand" -a "init" -d "Initialize and install dotfiles"
complete -c dot -n "__fish_use_subcommand" -a "update" -d "Update dotfiles, packages, pi, and Pocock skills"
complete -c dot -n "__fish_use_subcommand" -a "doctor" -d "Run diagnostics and check installation"
complete -c dot -n "__fish_use_subcommand" -a "package" -d "Package management commands"
complete -c dot -n "__fish_use_subcommand" -a "check-packages" -d "Check which packages are installed/missing"
complete -c dot -n "__fish_use_subcommand" -a "retry-failed" -d "Retry failed package installations"
complete -c dot -n "__fish_use_subcommand" -a "benchmark-shell" -d "Benchmark Fish shell startup performance"
complete -c dot -n "__fish_use_subcommand" -a "gen-ssh-key" -d "Generate SSH key for GitHub/GitLab with email"
complete -c dot -n "__fish_use_subcommand" -a "stow" -d "Create symlinks for dotfiles using GNU Stow"
complete -c dot -n "__fish_use_subcommand" -a "completions" -d "Generate Fish shell completions"
complete -c dot -n "__fish_use_subcommand" -a "link" -d "Install dot command globally (create symlink in PATH)"
complete -c dot -n "__fish_use_subcommand" -a "unlink" -d "Uninstall global dot command (remove symlink)"
complete -c dot -n "__fish_use_subcommand" -a "edit" -d "Open dotfiles in editor"
complete -c dot -n "__fish_use_subcommand" -a "help" -d "Show help message"

# Global options
complete -c dot -n "__fish_use_subcommand" -l "skip-ssh" -d "Skip SSH key generation"
complete -c dot -n "__fish_use_subcommand" -l "skip-font" -d "Skip font installation"
complete -c dot -n "__fish_use_subcommand" -l "version" -d "Show version information"
complete -c dot -n "__fish_use_subcommand" -s "h" -l "help" -d "Show help message"

# Package subcommands
complete -c dot -n "__fish_seen_subcommand_from package" -n "not __fish_seen_subcommand_from add remove update list help" -a "add" -d "Add a package to the nix config and apply"
complete -c dot -n "__fish_seen_subcommand_from package" -n "not __fish_seen_subcommand_from add remove update list help" -a "remove" -d "Remove a package from the nix config and apply"
complete -c dot -n "__fish_seen_subcommand_from package" -n "not __fish_seen_subcommand_from add remove update list help" -a "update" -d "Update flake inputs and apply"
complete -c dot -n "__fish_seen_subcommand_from package" -n "not __fish_seen_subcommand_from add remove update list help" -a "list" -d "List packages declared in the nix config"
complete -c dot -n "__fish_seen_subcommand_from package" -n "not __fish_seen_subcommand_from add remove update list help" -a "help" -d "Show package help"

# Package add type completions
complete -c dot -n "__fish_seen_subcommand_from package; and __fish_seen_subcommand_from add" -n "not __fish_seen_subcommand_from pkg brew cask" -a "pkg" -d "nixpkgs attribute (environment.systemPackages)"
complete -c dot -n "__fish_seen_subcommand_from package; and __fish_seen_subcommand_from add" -n "not __fish_seen_subcommand_from pkg brew cask" -a "brew" -d "Homebrew formula"
complete -c dot -n "__fish_seen_subcommand_from package; and __fish_seen_subcommand_from add" -n "not __fish_seen_subcommand_from pkg brew cask" -a "cask" -d "Homebrew cask"

# Benchmark-shell command options
complete -c dot -n "__fish_seen_subcommand_from benchmark-shell" -s "r" -l "runs" -d "Number of benchmark runs" -xa "5 10 15 20 25 30"
complete -c dot -n "__fish_seen_subcommand_from benchmark-shell" -s "v" -l "verbose" -d "Show detailed timing for each run"
complete -c dot -n "__fish_seen_subcommand_from benchmark-shell" -s "h" -l "help" -d "Show benchmark-shell help"

# Gen-ssh-key command options
complete -c dot -n "__fish_seen_subcommand_from gen-ssh-key" -s "h" -l "help" -d "Show gen-ssh-key help"

# Dynamic completions for declared packages (when removing)
function __dot_declared_packages
    set -l dir (dirname (status -f))/../../../..
    set -l nixdir "$HOME/.dotfiles/nix"
    grep -hE '^    [a-zA-Z0-9]' "$nixdir/packages.nix" 2>/dev/null | string trim
    grep -hE '^[[:space:]]+"' "$nixdir/homebrew.nix" 2>/dev/null | string trim | string trim -c '"' | string replace -r '#.*' ''
end

complete -c dot -n "__fish_seen_subcommand_from package; and __fish_seen_subcommand_from remove" -xa "(__dot_declared_packages)"
