alias c 'clear'
alias code 'vim'
alias grep 'grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias pbc 'pbcopy'
alias pbp 'pbpaste'
alias pn 'pnpm'
alias scratch 'nvim -c "setlocal buftype=nofile"'
alias vimdiff 'nvim -d'
